web:
  build: ./app
  volumes:
    - "./app:/src/app"
  # ports:
  #   - "3030:3000"
  command: npm run start:prod
  links:
    - redis:redis

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web

redis:
  image: redis
  ports:
    - "6379"
